#!/usr/bin/env bash
# Clean one-shot setup for the demo: validate the two locally built debug
# binaries, then write .env. The default (ducklake) path needs NO credentials.
#
# Usage, from the repo root:
#   DBT_BIN=/path/to/fs/target/debug/dbt \
#   DUCKDB_BUILD_DIR=/path/to/duckdb-iceberg \
#   scripts/setup.sh
#
# Then:
#   set -a && source .env && set +a        # (or: direnv allow)
#   "$DBT_BIN" seed && "$DBT_BIN" run
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

: "${DBT_BIN:?set DBT_BIN to your built fs 'dbt' binary — see README > Build the two local binaries}"
: "${DUCKDB_BUILD_DIR:?set DUCKDB_BUILD_DIR to your duckdb-iceberg checkout — see README > Build the two local binaries}"

SRC="$DUCKDB_BUILD_DIR/build/debug/src"

[ -x "$DBT_BIN" ] || {
  echo "error: DBT_BIN is not an executable file: $DBT_BIN" >&2
  echo "  build it with: cargo build --bin dbt   (in your fs checkout)" >&2
  exit 1
}
# dbt's xdbc loader looks for libduckdb.<dylib|so> inside ADBC_REPOSITORY; the
# build dir already contains it, so no symlink is needed.
ls "$SRC"/libduckdb.* >/dev/null 2>&1 || {
  echo "error: no libduckdb.{dylib,so} under $SRC" >&2
  echo "  build it with: DISABLE_SANITIZER=1 make debug   (in $DUCKDB_BUILD_DIR)" >&2
  echo "  (DISABLE_SANITIZER=1 is required — an ASAN build can't be dlopen'd by dbt)" >&2
  exit 1
}

if [ -e "$ROOT/.env" ]; then
  echo "note: $ROOT/.env already exists — leaving it untouched (delete it to regenerate)."
else
  umask 077
  cat > "$ROOT/.env" <<EOF
# Generated by scripts/setup.sh. For external catalogs, add their secrets from .env.example.
DBT_BIN=$DBT_BIN
DUCKDB_BUILD_DIR=$DUCKDB_BUILD_DIR
ADBC_REPOSITORY=$SRC
DISABLE_CDN_DRIVER_CACHE=true
DISABLE_AUTO_DRIVER_REBUILD=true
DBT_PROFILES_DIR=$ROOT
DUCKDB_HOME=$ROOT/.tmp/duckdb-home
DUCKDB_CLI=$DUCKDB_BUILD_DIR/build/debug/duckdb
EOF
  echo "wrote $ROOT/.env"
fi

cat <<'EOF'

setup ok. next:
  set -a && source .env && set +a      # or: direnv allow
  "$DBT_BIN" seed && "$DBT_BIN" run     # builds into the default ducklake catalog (no creds)

external catalogs (horizon / polaris / unity / s3_tables): copy their vars from
.env.example into .env, then uncomment the matching block in catalogs.yml and
profiles.yml. see README > Switching catalogs.
EOF
