#!/usr/bin/env bash
# Clean one-shot setup for the demo: check for the dbt Fusion CLI, then write
# .env. The default (ducklake) path needs NO credentials. The DuckDB driver is
# the official DuckDB 1.5.4 release, fetched from the dbt CDN.
#
# Usage, from the repo root:
#   scripts/setup.sh
#
# Then:
#   set -a && source .env && set +a        # (or: direnv allow)
#   dbt seed && dbt run
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

command -v dbt >/dev/null 2>&1 || {
  echo "error: no 'dbt' on PATH — see README > Install dbt" >&2
  echo "  curl -fsSL https://public.cdn.getdbt.com/fs/install/install.sh | sh -s -- --update" >&2
  exit 1
}

if [ -e "$ROOT/.env" ]; then
  echo "note: $ROOT/.env already exists — leaving it untouched (delete it to regenerate)."
else
  umask 077
  cat > "$ROOT/.env" <<EOF
# Generated by scripts/setup.sh. For external catalogs, add their secrets from .env.example.
DBT_PROFILES_DIR=$ROOT
DUCKDB_HOME=$ROOT/.tmp/duckdb-home
EOF
  echo "wrote $ROOT/.env"
fi

cat <<'EOF'

setup ok. next:
  set -a && source .env && set +a      # or: direnv allow
  dbt seed && dbt run                  # builds into the default ducklake catalog (no creds)

external catalogs (horizon / mdls / unity / s3_tables): copy their vars from
.env.example into .env, then uncomment the matching block in catalogs.yml and
profiles.yml. see README > Switching catalogs.
EOF
