#!/usr/bin/env bash
# Clean one-shot setup for the demo: validate the locally built dbt binary,
# then write .env. The default (ducklake) path needs NO credentials. The DuckDB
# driver is the official DuckDB 1.5.4 release, fetched from the dbt CDN.
#
# Usage, from the repo root:
#   DBT_BIN=/path/to/fs/target/debug/dbt \
#   scripts/setup.sh
#
# Then:
#   set -a && source .env && set +a        # (or: direnv allow)
#   "$DBT_BIN" seed && "$DBT_BIN" run
set -euo pipefail

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

: "${DBT_BIN:?set DBT_BIN to your built fs 'dbt' binary — see README > Build the dbt binary}"

[ -x "$DBT_BIN" ] || {
  echo "error: DBT_BIN is not an executable file: $DBT_BIN" >&2
  echo "  build it with: cargo build --bin dbt   (in your fs checkout)" >&2
  exit 1
}

if [ -e "$ROOT/.env" ]; then
  echo "note: $ROOT/.env already exists — leaving it untouched (delete it to regenerate)."
else
  umask 077
  cat > "$ROOT/.env" <<EOF
# Generated by scripts/setup.sh. For external catalogs, add their secrets from .env.example.
DBT_BIN=$DBT_BIN
DBT_PROFILES_DIR=$ROOT
DUCKDB_HOME=$ROOT/.tmp/duckdb-home
EOF
  echo "wrote $ROOT/.env"
fi

cat <<'EOF'

setup ok. next:
  set -a && source .env && set +a      # or: direnv allow
  "$DBT_BIN" seed && "$DBT_BIN" run     # builds into the default ducklake catalog (no creds)

external catalogs (horizon / polaris / unity / s3_tables): copy their vars from
.env.example into .env, then uncomment the matching block in catalogs.yml and
profiles.yml. see README > Switching catalogs.
EOF
